### ISSUE TITLE
Fail over support 

### ISSUE THREAD

**Issue by avoxm** [gigya/KafkaNetClient#11]
Does the library supports automatic fail over ? Let's say one of the brokers went down will it recognize the new lead broker ?

**Comment by EranOfer** [comment]
hi @avoxm,
- The consumer knows how to recover from failures.
- The producer uses ProtocolGateway which does the recovery.

You can look at the code it's pretty straightforward:
https://github.com/gigya/KafkaNetClient/blob/master/src/KafkaNetClient/ProtocolGateway.cs

**Comment by EranOfer** [comment]
can i close this issue, or do you have any more questions?
