### ISSUE TITLE
Use `ConfigureAwait(false)` in async operations

### ISSUE THREAD

**Issue by randa1** [gigya/KafkaNetClient#8]
Following the discussion in gigya/Orleans.KafkaStreamProvider#16:

> when you are writing a general purpose library, you basically have no other choice - you don't know how it will be used, and in what scheduler the calling code will be running, so you basically have to use ConfigureAwait(false). I actually did not see THE EXPLICIT .NET guideline about it anywhere (maybe it exists somewhere), but my general understanding is that this is how you are supposed to write libraries. I have seen a lot of libraries using this principle. In your case, the Kafka Client is such a general purpose library.

**Comment by gabikliot** [comment]
http://www.infoq.com/articles/Async-API-Design

https://channel9.msdn.com/Series/Three-Essential-Tips-for-Async/Async-library-methods-should-consider-using-Task-ConfigureAwait-false-

http://stackoverflow.com/questions/30036459/should-we-use-configureawaitfalse-in-libraries-that-call-async-callbacks
http://stackoverflow.com/questions/32269292/disable-capturing-context-in-all-library-code-configureawaitfalse
http://stackoverflow.com/questions/13489065/best-practice-to-call-configureawait-for-all-server-side-code
https://github.com/code-cracker/code-cracker/issues/235

I think that pretty much proves the point.
